//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDNUtils.DBSqlServer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DBSqlServerLocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBSqlServerLocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WDNUtils.DBSqlServer.Localization.DBSqlServerLocalizedText", typeof(DBSqlServerLocalizedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error binding parameter {0}.
        /// </summary>
        internal static string DBSqlServerCommand_BindError {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_BindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error closing DataReader.
        /// </summary>
        internal static string DBSqlServerCommand_CloseDataReader {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_CloseDataReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing the connection reference from the database command.
        /// </summary>
        internal static string DBSqlServerCommand_ConnectionClear_Error {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_ConnectionClear_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error disposing DataAdapter.
        /// </summary>
        internal static string DBSqlServerCommand_DataAdapter_Disposal_Error {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_DataAdapter_Disposal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error disposing database command.
        /// </summary>
        internal static string DBSqlServerCommand_Disposal_Error {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_Disposal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error disposing DataReader.
        /// </summary>
        internal static string DBSqlServerCommand_DisposeDataReader {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_DisposeDataReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating database command object.
        /// </summary>
        internal static string DBSqlServerCommand_Error {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error running non-query statement.
        /// </summary>
        internal static string DBSqlServerCommand_ExecuteNonQuery_Error {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_ExecuteNonQuery_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating DataAdapter.
        /// </summary>
        internal static string DBSqlServerCommand_GetDataSet_DataAdapterError {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_GetDataSet_DataAdapterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving data rows from query.
        /// </summary>
        internal static string DBSqlServerCommand_GetDataSet_DataRetrieveError {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_GetDataSet_DataRetrieveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database connection must not be null.
        /// </summary>
        internal static string DBSqlServerCommand_NullConnection {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_NullConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter list for the command has a null element!.
        /// </summary>
        internal static string DBSqlServerCommand_NullParameter {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_NullParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error cleaning the command parameters collection.
        /// </summary>
        internal static string DBSqlServerCommand_ParameterCollectionClear_Error {
            get {
                return ResourceManager.GetString("DBSqlServerCommand_ParameterCollectionClear_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database connection is closed.
        /// </summary>
        internal static string DBSqlServerConnection_BeginTransaction_Closed {
            get {
                return ResourceManager.GetString("DBSqlServerConnection_BeginTransaction_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting database transaction.
        /// </summary>
        internal static string DBSqlServerConnection_BeginTransaction_Error {
            get {
                return ResourceManager.GetString("DBSqlServerConnection_BeginTransaction_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error closing database connection.
        /// </summary>
        internal static string DBSqlServerConnection_Close_Error {
            get {
                return ResourceManager.GetString("DBSqlServerConnection_Close_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database connection was closed without committing the transaction. The transaction was rolled back automatically..
        /// </summary>
        internal static string DBSqlServerConnection_ClosedWithActiveTransaction {
            get {
                return ResourceManager.GetString("DBSqlServerConnection_ClosedWithActiveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot stablish connection to the database.
        /// </summary>
        internal static string DBSqlServerConnection_Constructor_Error {
            get {
                return ResourceManager.GetString("DBSqlServerConnection_Constructor_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the database savepoint {0}.
        /// </summary>
        internal static string DBSqlServerConnection_CreateSavepoint_Error {
            get {
                return ResourceManager.GetString("DBSqlServerConnection_CreateSavepoint_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error disposing database connection resources.
        /// </summary>
        internal static string DBSqlServerConnection_Disposal_Error {
            get {
                return ResourceManager.GetString("DBSqlServerConnection_Disposal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string must not be empty.
        /// </summary>
        internal static string DBSqlServerConnection_EmptyConnectionString {
            get {
                return ResourceManager.GetString("DBSqlServerConnection_EmptyConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error rolling back database transaction.
        /// </summary>
        internal static string DBSqlServerConnection_Rollback_Error {
            get {
                return ResourceManager.GetString("DBSqlServerConnection_Rollback_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected null value for the column &apos;{0}&apos;!.
        /// </summary>
        internal static string DBSqlServerDataReader_ColumnIsNull {
            get {
                return ResourceManager.GetString("DBSqlServerDataReader_ColumnIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column &apos;{0}&apos; does not exist in the data set!.
        /// </summary>
        internal static string DBSqlServerDataReader_ColumnNotFound {
            get {
                return ResourceManager.GetString("DBSqlServerDataReader_ColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database server refused the connection. Error: {0}..
        /// </summary>
        internal static string DBSqlServerException_DatabaseDown {
            get {
                return ResourceManager.GetString("DBSqlServerException_DatabaseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the database, please check the network connection.{0}Error: {1}..
        /// </summary>
        internal static string DBSqlServerException_NetworkError {
            get {
                return ResourceManager.GetString("DBSqlServerException_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is a {1}, and cannot be converted to {2}.
        /// </summary>
        internal static string DBSqlServerParameter_CastError {
            get {
                return ResourceManager.GetString("DBSqlServerParameter_CastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the parameter &apos;{0}&apos; has {1} characters but the maximum size is {2} characters.
        /// </summary>
        internal static string DBSqlServerParameter_InvalidMaxSizeString {
            get {
                return ResourceManager.GetString("DBSqlServerParameter_InvalidMaxSizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter name cannot be null or empty.
        /// </summary>
        internal static string DBSqlServerParameter_InvalidName {
            get {
                return ResourceManager.GetString("DBSqlServerParameter_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the parameter &apos;{0}&apos; cannot be changed because it is not an input type parameter (Direction.Input ou Direction.InputOutput).
        /// </summary>
        internal static string DBSqlServerParameter_InvalidParameterDirectionSetValue {
            get {
                return ResourceManager.GetString("DBSqlServerParameter_InvalidParameterDirectionSetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error disposing the bind parameter {0}.
        /// </summary>
        internal static string DBSqlServerParameter_ParameterDisposalError {
            get {
                return ResourceManager.GetString("DBSqlServerParameter_ParameterDisposalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error cleaning the value of the bind parameter {0}.
        /// </summary>
        internal static string DBSqlServerParameter_ValueCleanupError {
            get {
                return ResourceManager.GetString("DBSqlServerParameter_ValueCleanupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error disposing the value of the bind parameter {0}.
        /// </summary>
        internal static string DBSqlServerParameter_ValueDisposalError {
            get {
                return ResourceManager.GetString("DBSqlServerParameter_ValueDisposalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot commit because the transaction was already finished.
        /// </summary>
        internal static string DBSqlServerTransaction_Commit_AlreadyFinished {
            get {
                return ResourceManager.GetString("DBSqlServerTransaction_Commit_AlreadyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error committing database transaction.
        /// </summary>
        internal static string DBSqlServerTransaction_Commit_Error {
            get {
                return ResourceManager.GetString("DBSqlServerTransaction_Commit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rollback the savepoint {0} because the transaction was already finished.
        /// </summary>
        internal static string DBSqlServerTransaction_RollbackSavepoint_AlreadyFinished {
            get {
                return ResourceManager.GetString("DBSqlServerTransaction_RollbackSavepoint_AlreadyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error rolling back to the database savepoint {0}.
        /// </summary>
        internal static string DBSqlServerTransaction_RollbackSavepoint_Error {
            get {
                return ResourceManager.GetString("DBSqlServerTransaction_RollbackSavepoint_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rollback the transaction because it was already finished.
        /// </summary>
        internal static string DBSqlServerTransaction_RollbackTransaction_AlreadyFinished {
            get {
                return ResourceManager.GetString("DBSqlServerTransaction_RollbackTransaction_AlreadyFinished", resourceCulture);
            }
        }
    }
}
